### ISSUE TITLE
 Anchor element not declared error

### ISSUE THREAD

**Issue by ebenezer-melkamu** [DeepBlueCLtd/LegacyMan#276] opened 2023-08-01 09:43 UTC
We have an instance in the html where an empty `<a>` link is being used to define an anchor, rather than a link.

We found the `<anchor>` element, to be used to handle that.  When trying to create an `<anchor>` element, the code is throwing this error: `anchor element is not declared`

Aah, it's not an `anchor` that we should be using - that is just for use in `ditamap` files.

Instead we should be providing an `id="something"` attribute in the parent `<entry>` element.

This issue arose in file `Britain_Standalones.html`.

Ian to double-check this pattern in the real data, and verify it's `name` not `id` that is being used.

**Comment by IanMayo** [comment] 2023-08-30 09:07
Close. Duplicate of #288

**Closed as completed by IanMayo** 2023-08-30 09:07 UTC
Labels: enhancement, onsite
